### ISSUE TITLE
Spider gif sizing

### ISSUE THREAD

**Issue by mattada** [factor1/phxdw-2017#1]
@stuffers81 looks like the spider gif is a lot smaller than the others. Could be an artboard issues since it is 300x300 as expected. Can you check? 

http://phxdw.com/

**Comment by stuffers81** [comment]
I increased the size to 500x500. It fills up my entire artboard, AE file, and GIF. I just checked the link you sent (not sure if it auto updates once I upload the new GIF) but it does look small. I don't understand why this particular one would look smaller when all the AI files and AE files are the exact same size.
